/**
 * File: app/controller/CarListingsController.js
 */
Ext.define("CarListingApp.controller.CarListingsController", {
    extend: "CarListingApp.controller.AbstractAppController",
    requires: ["CarListingApp.model.CarData", "CarListingApp.model.CarChart"],
    config: {
        /**
         * The {CarListingApp.model.Scenario} being displayed by the view.
         */
        scenario: null
    },
    control: {
        listingGrid: {
            select: "onGridSelect"
        },
        detailPanel: true,
        qualityChart: true
    },
    init: function() {
        return this.callParent(arguments);
    },
    /**
     * Performs initial view setup.
     */
    onGridSelect: function(rowmodel, record, index, eOpts) {
        // Grab a reference to the detailPanel via the getter that is
        // generated by the component's itemId in the view.
        var detailPanel = this.getDetailPanel();
        // Update the detailPanel with data this will trigger the tpl to
        // become updates
        detailPanel.update(record.data);
        // grab a reference to the qualityChart, notice we use down here
        // instead of child because down will go down the container
        // hierarchy at any depth and child will only retrieve direct
        // children.
        var chart = this.getQualityChart();
        // get the quality field out of this record
        var qualityData = record.get('quality');
        chart.store.loadData(qualityData);
    }
});
